[Interface]
Address = 10.8.1.2/32
DNS = 1.1.1.1, 1.0.0.1
PrivateKey = dVGpksPMKmgpjtS/GCl+Nme8oyJ3FrqnfjOZtOsbuQE=

[Peer]
PublicKey = Oj0uEaXMggpKfw+kKZtFwEuwkndOXOjZTMKRE/ReeC0=
PresharedKey = AgDaGM7xfR7djZvONiU16qJxx8P6yL/bRF8gtJD3PCc=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 193.233.115.130:32564
PersistentKeepalive = 25
